"""add_distribution_request

Revision ID: 8a1aecc8b7fc
Revises: dfc042a00019
Create Date: 2026-08-03 22:12:35.264651

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a1aecc8b7fc'
down_revision: str | Sequence[str] | None = 'dfc042a00019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('root_type', sa.String(length=16), nullable=False),
    sa.Column('root_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('target_site_id', sa.String(length=128), nullable=True),
    sa.Column('office_profile_version_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('bundle_object_id', sa.String(length=36), nullable=True),
    sa.Column('bundle_path', sa.Text(), nullable=True),
    sa.Column('bundle_size_bytes', sa.Integer(), nullable=True),
    sa.Column('bundle_checksum', sa.String(length=64), nullable=True),
    sa.Column('manifest_summary', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution_requests')
    # ### end Alembic commands ###
