"""add_platform_settings

Revision ID: eba969aa8e91
Revises: ce52d6d1f75a
Create Date: 2026-08-10 11:22:14.751964

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eba969aa8e91'
down_revision: str | Sequence[str] | None = 'ce52d6d1f75a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    open-decisions.md D-065 UPDATE / D-075 — P15 관리자 설정에 처음으로 저장소가
    생긴 하위 영역(인덱싱 임베딩 모델)을 위한 일반 key/value 테이블. 첫 번째(현재
    유일한) key는 `portal_api.platform_settings.INDEXING_EMBED_MODEL_KEY`
    (`"indexing_embedding_model"`) — 값이 없으면 indexing-runtime 자체 기본값이
    적용된다(하위 호환, 기존 인덱싱 동작 변화 없음). 신규 테이블이라 기존 행 백필이
    필요 없다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=256), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
